### ISSUE TITLE
redfish-lld error

### ISSUE THREAD

**Issue by to0b** [spectroman/redfish-idrac-lld#1]
When I try to execute the lld script directly with username, pw, ipmi SimpleStorage I'll get the following error:

Traceback (most recent call last):
        6: from ./redfish-lld:57:in `<main>'
        5: from /usr/lib/ruby/2.5.0/net/http.rb:609:in `start'
        4: from /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
        3: from /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
        2: from /usr/lib/ruby/2.5.0/net/http.rb:981:in `connect'
        1: from /usr/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write finished (OpenSSL::SSL::SSLError)

and sometimes this error:

Traceback (most recent call last):
./redfish-lld:94:in `<main>': undefined method `each' for nil:NilClass (NoMethodError)

**Comment by spectroman** [comment]
I have seen timeout problems in some servers as well.

One thing you could try to do is to increase the timeout from the HTTP connectors:

line 57 and line 103, increase the 'timeout' value.

If that's the case and he start to work on the console, it might be that Zabbix will not be able to collect data from some servers, because the timeout value of Zabbix executing thing like that is very short (I actually have a patch to fix this).

If that doesn't fix the problem, it could be a problem with some versions, from openssl an/or ruby modules behind this.

I have it running stable in the following:
```
[root@proxy-a ~]# openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
[root@proxy-a ~]# ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
OpenSSL 1.0.2k  26 Jan 2017
[root@proxy-a ~]#
```

**Comment by to0b** [comment]
The timeout trick did it, thanks!

But we have two iDRAC 7 Servers with Firmware Version 2.61.60.60 where the redfish-lld SimpleStorage returns always:
`Traceback (most recent call last):
./redfish-lld:94:in `<main>': undefined method `each' for nil:NilClass (NoMethodError)`

Other iDRAC 7 Servers with Firmware 2.52.52.52 are working fine.

**Comment by gorokhovdenis** [comment]
> The timeout trick did it, thanks!
> 
> But we have two iDRAC 7 Servers with Firmware Version 2.61.60.60 where the redfish-lld SimpleStorage returns always:
> `Traceback (most recent call last): ./redfish-lld:94:in `
> ': undefined method `each' for nil:NilClass (NoMethodError)`
> 
> Other iDRAC 7 Servers with Firmware 2.52.52.52 are working fine.

You need to modify line 41 in redfish-lld script 
` APIURL="/redfish/v1/Systems/System.Embedded.1/SimpleStorage/Controllers"`
